-- La sala di prova, fotografata il 18/08/2026 PRIMA di toccare
-- `prova:ricostruisci --azzera` (giro A del mandato sala).
--
-- ⚠️ Perche' esiste: il giro A nasce per non perdere piu' la disposizione
-- della sala, e sarebbe una beffa perderla proprio mentre lo si costruisce.
-- Rilievo del validatore, 18/08.
--
-- ⚠️ Solo `dining_tables`, cioe' la sala DI SEMPRE. Gli scostamenti di una
-- giornata (`disposizioni_giornaliere`) non stanno qui apposta: sono la
-- disposizione di un martedi', non la sala.
--
-- Si rimette con:  psql "<stringa di collegamento>" -f docs/collaudo/copie/sala-prova.sql
insert into dining_tables (id, label, tipo, forma, zona, larghezza_cm, profondita_cm, x, y, ruotato, spostabile, posti_fissi, active) values ('02dd4520-49ab-499c-bbba-2d057befb542'::uuid, 'Chef Table', 'chef_table', 'rettangolo', 'bancone', 200, 70, 980, 530, false, false, 4, true) on conflict (id) do update set label=excluded.label, x=excluded.x, y=excluded.y, ruotato=excluded.ruotato, zona=excluded.zona;
insert into dining_tables (id, label, tipo, forma, zona, larghezza_cm, profondita_cm, x, y, ruotato, spostabile, posti_fissi, active) values ('7431a4b6-4627-4253-ad4d-750119f98727'::uuid, 'Divano 1', 'divano', 'rettangolo', 'divani', 240, 200, 300, 800, false, false, 6, true) on conflict (id) do update set label=excluded.label, x=excluded.x, y=excluded.y, ruotato=excluded.ruotato, zona=excluded.zona;
insert into dining_tables (id, label, tipo, forma, zona, larghezza_cm, profondita_cm, x, y, ruotato, spostabile, posti_fissi, active) values ('eeba964f-c299-4d52-b3f2-1271d4cfb547'::uuid, 'Divano 2', 'divano', 'rettangolo', 'divani', 240, 200, 620, 800, false, false, 6, true) on conflict (id) do update set label=excluded.label, x=excluded.x, y=excluded.y, ruotato=excluded.ruotato, zona=excluded.zona;
insert into dining_tables (id, label, tipo, forma, zona, larghezza_cm, profondita_cm, x, y, ruotato, spostabile, posti_fissi, active) values ('9f71bd03-a299-421f-bc99-8faf683ba878'::uuid, 'Divano 3', 'divano', 'rettangolo', 'divani', 240, 200, 940, 800, false, false, 6, true) on conflict (id) do update set label=excluded.label, x=excluded.x, y=excluded.y, ruotato=excluded.ruotato, zona=excluded.zona;
insert into dining_tables (id, label, tipo, forma, zona, larghezza_cm, profondita_cm, x, y, ruotato, spostabile, posti_fissi, active) values ('5ec14ddf-f8e4-41ec-9610-6b3ff738c3bc'::uuid, 'T1', 'tavolo', 'rettangolo', 'sala_alta', 180, 90, 1450, 90, true, true, null, true) on conflict (id) do update set label=excluded.label, x=excluded.x, y=excluded.y, ruotato=excluded.ruotato, zona=excluded.zona;
insert into dining_tables (id, label, tipo, forma, zona, larghezza_cm, profondita_cm, x, y, ruotato, spostabile, posti_fissi, active) values ('4b9d8da3-fecf-499c-baa3-a404b56a98cd'::uuid, 'T2', 'tavolo', 'rettangolo', 'sala_alta', 180, 90, 1750, 90, true, true, null, true) on conflict (id) do update set label=excluded.label, x=excluded.x, y=excluded.y, ruotato=excluded.ruotato, zona=excluded.zona;
insert into dining_tables (id, label, tipo, forma, zona, larghezza_cm, profondita_cm, x, y, ruotato, spostabile, posti_fissi, active) values ('1fe13ed8-77a7-48b1-b547-7bdc4664d7c3'::uuid, 'T3', 'tavolo', 'rettangolo', 'sala_alta', 90, 90, 1490, 300, false, true, null, true) on conflict (id) do update set label=excluded.label, x=excluded.x, y=excluded.y, ruotato=excluded.ruotato, zona=excluded.zona;
insert into dining_tables (id, label, tipo, forma, zona, larghezza_cm, profondita_cm, x, y, ruotato, spostabile, posti_fissi, active) values ('d9b57101-19f7-4548-9dfd-a9cd845cd275'::uuid, 'T4', 'tavolo', 'rettangolo', 'sala_alta', 90, 90, 1790, 300, false, true, null, true) on conflict (id) do update set label=excluded.label, x=excluded.x, y=excluded.y, ruotato=excluded.ruotato, zona=excluded.zona;
insert into dining_tables (id, label, tipo, forma, zona, larghezza_cm, profondita_cm, x, y, ruotato, spostabile, posti_fissi, active) values ('0c5a922e-8e6a-4766-81c5-7cb21f91a723'::uuid, 'T5', 'tavolo', 'rettangolo', 'sala_bassa', 90, 90, 1150, 600, false, true, null, true) on conflict (id) do update set label=excluded.label, x=excluded.x, y=excluded.y, ruotato=excluded.ruotato, zona=excluded.zona;
insert into dining_tables (id, label, tipo, forma, zona, larghezza_cm, profondita_cm, x, y, ruotato, spostabile, posti_fissi, active) values ('a8d15b91-094e-47f0-9f0f-5f2deef995d1'::uuid, 'T6', 'tavolo', 'rettangolo', 'sala_bassa', 90, 90, 1240, 600, false, true, null, true) on conflict (id) do update set label=excluded.label, x=excluded.x, y=excluded.y, ruotato=excluded.ruotato, zona=excluded.zona;
insert into dining_tables (id, label, tipo, forma, zona, larghezza_cm, profondita_cm, x, y, ruotato, spostabile, posti_fissi, active) values ('3d67f9cf-44fc-466c-a642-85a2088c2b7b'::uuid, 'T7', 'tavolo', 'rettangolo', 'sala_bassa', 90, 90, 1330, 600, false, true, null, true) on conflict (id) do update set label=excluded.label, x=excluded.x, y=excluded.y, ruotato=excluded.ruotato, zona=excluded.zona;
insert into dining_tables (id, label, tipo, forma, zona, larghezza_cm, profondita_cm, x, y, ruotato, spostabile, posti_fissi, active) values ('6a3d6c68-9c73-4cd1-9a48-f9d87032c067'::uuid, 'T8', 'tavolo', 'rettangolo', 'sala_bassa', 90, 90, 1550, 600, false, true, null, true) on conflict (id) do update set label=excluded.label, x=excluded.x, y=excluded.y, ruotato=excluded.ruotato, zona=excluded.zona;
insert into dining_tables (id, label, tipo, forma, zona, larghezza_cm, profondita_cm, x, y, ruotato, spostabile, posti_fissi, active) values ('3a022a5f-963f-4639-a749-de5d39fcc836'::uuid, 'T9', 'tavolo', 'rettangolo', 'sala_bassa', 90, 90, 1640, 600, false, true, null, true) on conflict (id) do update set label=excluded.label, x=excluded.x, y=excluded.y, ruotato=excluded.ruotato, zona=excluded.zona;
