-- La sala di produzione, fotografata il 18/08/2026 PRIMA di toccare
-- `prova:ricostruisci --azzera` (giro A del mandato sala).
--
-- ⚠️ Perche' esiste: il giro A nasce per non perdere piu' la disposizione
-- della sala, e sarebbe una beffa perderla proprio mentre lo si costruisce.
-- Rilievo del validatore, 18/08.
--
-- ⚠️ Solo `dining_tables`, cioe' la sala DI SEMPRE. Gli scostamenti di una
-- giornata (`disposizioni_giornaliere`) non stanno qui apposta: sono la
-- disposizione di un martedi', non la sala.
--
-- Si rimette con:  psql "<stringa di collegamento>" -f docs/collaudo/copie/sala-produzione.sql
insert into dining_tables (id, label, tipo, forma, zona, larghezza_cm, profondita_cm, x, y, ruotato, spostabile, posti_fissi, active) values ('e8642209-0a31-43a1-ab32-59cb591ee782'::uuid, 'Chef Table', 'chef_table', 'rettangolo', 'bancone', 200, 70, 980, 530, false, false, 4, true) on conflict (id) do update set label=excluded.label, x=excluded.x, y=excluded.y, ruotato=excluded.ruotato, zona=excluded.zona;
insert into dining_tables (id, label, tipo, forma, zona, larghezza_cm, profondita_cm, x, y, ruotato, spostabile, posti_fissi, active) values ('470e34b1-aed5-4a3b-ba1b-38a9b5b0698a'::uuid, 'Divano 1', 'divano', 'rettangolo', 'divani', 240, 200, 300, 800, false, false, 6, true) on conflict (id) do update set label=excluded.label, x=excluded.x, y=excluded.y, ruotato=excluded.ruotato, zona=excluded.zona;
insert into dining_tables (id, label, tipo, forma, zona, larghezza_cm, profondita_cm, x, y, ruotato, spostabile, posti_fissi, active) values ('00cf167e-d55e-448a-925a-d324b2c5a005'::uuid, 'Divano 2', 'divano', 'rettangolo', 'divani', 240, 200, 620, 800, false, false, 6, true) on conflict (id) do update set label=excluded.label, x=excluded.x, y=excluded.y, ruotato=excluded.ruotato, zona=excluded.zona;
insert into dining_tables (id, label, tipo, forma, zona, larghezza_cm, profondita_cm, x, y, ruotato, spostabile, posti_fissi, active) values ('3f27695e-ab6c-4543-bdf6-e182d7937ae8'::uuid, 'Divano 3', 'divano', 'rettangolo', 'divani', 240, 200, 940, 800, false, false, 6, true) on conflict (id) do update set label=excluded.label, x=excluded.x, y=excluded.y, ruotato=excluded.ruotato, zona=excluded.zona;
insert into dining_tables (id, label, tipo, forma, zona, larghezza_cm, profondita_cm, x, y, ruotato, spostabile, posti_fissi, active) values ('6752c0af-a650-472d-96af-45b0343c1928'::uuid, 'T1', 'tavolo', 'rettangolo', 'sala_alta', 180, 90, 1860, 330, true, true, null, true) on conflict (id) do update set label=excluded.label, x=excluded.x, y=excluded.y, ruotato=excluded.ruotato, zona=excluded.zona;
insert into dining_tables (id, label, tipo, forma, zona, larghezza_cm, profondita_cm, x, y, ruotato, spostabile, posti_fissi, active) values ('f0e80235-e3e6-4ba5-a7eb-a2efbd35fcef'::uuid, 'T2', 'tavolo', 'rettangolo', 'sala_alta', 180, 90, 1610, 10, true, true, null, true) on conflict (id) do update set label=excluded.label, x=excluded.x, y=excluded.y, ruotato=excluded.ruotato, zona=excluded.zona;
insert into dining_tables (id, label, tipo, forma, zona, larghezza_cm, profondita_cm, x, y, ruotato, spostabile, posti_fissi, active) values ('13aa3a09-e9a6-4aba-88b1-a7062a2ecc36'::uuid, 'T3', 'tavolo', 'rettangolo', 'sala_alta', 90, 90, 1610, 380, false, true, null, true) on conflict (id) do update set label=excluded.label, x=excluded.x, y=excluded.y, ruotato=excluded.ruotato, zona=excluded.zona;
insert into dining_tables (id, label, tipo, forma, zona, larghezza_cm, profondita_cm, x, y, ruotato, spostabile, posti_fissi, active) values ('e3b42d68-b94d-487a-966e-2a375a5fc251'::uuid, 'T4', 'tavolo', 'rettangolo', 'sala_alta', 90, 90, 1860, 70, false, true, null, true) on conflict (id) do update set label=excluded.label, x=excluded.x, y=excluded.y, ruotato=excluded.ruotato, zona=excluded.zona;
insert into dining_tables (id, label, tipo, forma, zona, larghezza_cm, profondita_cm, x, y, ruotato, spostabile, posti_fissi, active) values ('029128a3-0158-444e-a21f-171ffa212391'::uuid, 'T5', 'tavolo', 'rettangolo', 'sala_bassa', 90, 90, 1330, 870, false, true, null, true) on conflict (id) do update set label=excluded.label, x=excluded.x, y=excluded.y, ruotato=excluded.ruotato, zona=excluded.zona;
insert into dining_tables (id, label, tipo, forma, zona, larghezza_cm, profondita_cm, x, y, ruotato, spostabile, posti_fissi, active) values ('266607b7-d457-4bbd-8d7d-6f33e51ceb22'::uuid, 'T6', 'tavolo', 'rettangolo', 'sala_bassa', 90, 90, 1330, 780, false, true, null, true) on conflict (id) do update set label=excluded.label, x=excluded.x, y=excluded.y, ruotato=excluded.ruotato, zona=excluded.zona;
insert into dining_tables (id, label, tipo, forma, zona, larghezza_cm, profondita_cm, x, y, ruotato, spostabile, posti_fissi, active) values ('8cdf65d3-754a-4067-acb7-52cc2bf27657'::uuid, 'T7', 'tavolo', 'rettangolo', 'sala_bassa', 90, 90, 1610, 870, false, true, null, true) on conflict (id) do update set label=excluded.label, x=excluded.x, y=excluded.y, ruotato=excluded.ruotato, zona=excluded.zona;
insert into dining_tables (id, label, tipo, forma, zona, larghezza_cm, profondita_cm, x, y, ruotato, spostabile, posti_fissi, active) values ('7f615089-69aa-43a3-ab4b-8c3dfa93b858'::uuid, 'T8', 'tavolo', 'rettangolo', 'sala_bassa', 90, 90, 1610, 780, false, true, null, true) on conflict (id) do update set label=excluded.label, x=excluded.x, y=excluded.y, ruotato=excluded.ruotato, zona=excluded.zona;
insert into dining_tables (id, label, tipo, forma, zona, larghezza_cm, profondita_cm, x, y, ruotato, spostabile, posti_fissi, active) values ('a0a1c0df-d9e2-43b3-897e-09f45baa3ef1'::uuid, 'T9', 'tavolo', 'rettangolo', 'sala_bassa', 90, 90, 1610, 690, false, true, null, true) on conflict (id) do update set label=excluded.label, x=excluded.x, y=excluded.y, ruotato=excluded.ruotato, zona=excluded.zona;
